### ISSUE TITLE
VisionCraft.useXLModel is not working

### ISSUE THREAD

**Issue by PrijensNakrani** [VisionCraft-org/flutter_vision_craft#5]
![Screenshot 2024-01-29 104927](https://github.com/VisionCraft-org/flutter_vision_craft/assets/106821160/11b2a85f-11c2-4627-a596-0598bc35d4c1)

All XL models not working

**Comment by KarlMathuthu** [comment]
We are working on that, Sorry for that.

**Comment by KarlMathuthu** [comment]
And also take note that some of the XLModels have been removed. Thanks.

**Comment by Player99p** [comment]
Is there any update on this issue of XL Model not working???

**Comment by KarlMathuthu** [comment]
We are working on that, Please be patient a little more.

**Comment by KarlMathuthu** [comment]
Hi there y'all, Try to inject the package and then test the available **XLModels** before i push this version on pub.dev

**Comment by PrijensNakrani** [comment]
I just imported this project and called useXLModel and gave a prompt but its giving me error and i checked also creatImage method it's working fine but all XLModels are not working

![Screenshot 2024-01-31 162213](https://github.com/VisionCraft-org/flutter_vision_craft/assets/106821160/74904607-f17c-44e1-9a45-f4c05f574670)

**Comment by KarlMathuthu** [comment]
Please wait for now, Let me test on my side and I'll come back to you guys shortly.

**Comment by PrijensNakrani** [comment]
any update on XLModels issue?

**Comment by KarlMathuthu** [comment]
Don't use the XLModels for now, we are working on the issue, I just take too long because most of my time is spent at work.

**Comment by KarlMathuthu** [comment]
It's fixed. Don't forget to subscribe for premium by contacting https://t.me/Metimol
